# Generated by Django 4.2.3 on 2023-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='acting',
            field=models.CharField(default='hi', max_length=20),
        ),
    ]
