# Generated by Django 4.2.3 on 2023-11-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Log'},
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invention.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastage',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invention.product'),
            preserve_default=False,
        ),
    ]
