# Generated by Django 4.2.3 on 2023-12-10 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0002_log_acting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 24, 33, 485912)),
        ),
    ]
