# Generated by Django 4.2.3 on 2023-12-10 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0003_alter_purchaseditem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 28, 8, 8964)),
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 28, 8, 8964)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 28, 8, 8964)),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 28, 8, 8964)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 20, 28, 8, 8964)),
        ),
    ]
