# Generated by Django 4.2.7 on 2023-12-11 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0005_alter_cart_due_date_alter_checkedoutlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 5, 1, 992289)),
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 5, 1, 992289)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 5, 1, 992289)),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 5, 1, 992289)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 5, 1, 992289)),
        ),
    ]
