# Generated by Django 4.2.7 on 2023-12-11 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0006_adminmails_alter_cart_due_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMails',
            new_name='AdminMail',
        ),
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 0, 46, 435690)),
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 0, 46, 435690)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 0, 46, 435690)),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 0, 46, 435690)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 0, 46, 435690)),
        ),
    ]
