# Generated by Django 4.2.7 on 2023-11-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
