# Generated by Django 4.2.7 on 2023-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0008_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time_logged',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
