# Generated by Django 4.2.3 on 2023-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0009_alter_category_created_at_alter_logs_time_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
