# Generated by Django 4.2.3 on 2023-11-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0011_wastage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
