# Generated by Django 4.2.7 on 2023-11-23 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invention', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Roll_number',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
