# Generated by Django 4.2.7 on 2023-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0013_remove_cart_roll_number_cart_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
