# Generated by Django 4.2.3 on 2023-11-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0016_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
