# Generated by Django 4.2.7 on 2023-12-01 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invention', '0017_delete_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedItems',
            new_name='PurchasedItem',
        ),
    ]
