# Generated by Django 4.2.3 on 2023-11-24 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0018_dummyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dummyitem',
            name='status',
        ),
        migrations.AddField(
            model_name='dummyitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
