# Generated by Django 4.2.3 on 2023-12-10 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invention', '0020_alter_log_created_at_checkedoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastage',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='wastage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
