# Generated by Django 4.2.3 on 2023-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0021_remove_wastage_roll_number_wastage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='status',
            field=models.CharField(choices=[('checked_in', 'checked_in'), ('checked_out', 'checked_out')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
